.TH AUTOGEN 1 "v\ 1.0.0" "Wed, May 14, 2014" "GNU"
.SH NAME
.B autogen
\- Generates files needed by autotools.
.SH SYNOPSIS
autogen [option] program_name main_src_name [other.c ....]
.br
.SH OPTIONS
-h, outputs a brief help message.
.br
-m, requires an argument being the manpage file name.
.br
-A, requires an argument being the filename that lists the other
.br
conributing authors.
.br
-d, a file to install in /usr/local/share.
.br
-x, files to 'EXTRA_BUILD'. You invoke this once for each file or use
.br
a quote protected space separated list of filenames. Do not include
.br
any man page input, this is handled automatically.
.br
.SH DESCRIPTION
The program does three tasks, it hardlinks most of the files needed by
.br
autotools in the current directory. Then it generates the AUTHORS file
.br
followed by Makefile.am. If the -m option has been selected it inserts
.br
the man_MAN macro.
.br
.SH EXAMPLES
Example:
.br
autogen -m autogen.1 -A AUTHORS.other autogen autogem.c sub.c
.br
The option -m1 states that there is a manpage, autogen(1) and that the
project name is autogen, the sources are autogen.c and sub.c.
.br
.P
.SH VERSION
This documentation describes
.B autogen
version 1.0.1
.SH "SEE ALSO"
myconfig(1)
.br
.SH AUTHOR
Robert L (Bob) Parker <rlp1938@gmail.com>
