#!/bin/bash
#
# build.sh - script to build a C program, options allow optimisation
#            or build for `gdb`.
# set defaults
debug=1;

# write actual usage
usage () {
	echo;
	echo "./fixmake [option]"; echo;
	echo options;
	echo -h print help message and exit;
	echo '-d, set debug mode (default)';
	echo '-o, set optimised mode (O2)';
}

# options string
options=':ohd'
# the leading ':' in options string is required for the errors cases.

while getopts $options option
do
	case $option in
		o  ) debug=0;;
		d  ) debug=1;;
		h  ) usage; exit;;
		\? ) echo "Unknown option: -$OPTARG" >&2; exit 1;;
		:  ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
		*  ) echo "Unimplemented option: -$OPTARG" >&2; exit 1;;
	esac
done

tofind=$(grep 'CFLAGS =' Makefile |grep -v AM_CFLAGS)

if [ $debug == 1 ]
then
	torepl="CFLAGS = -g -O0"
else
	torepl="CFLAGS = -O2"
fi
exp=s/"$tofind"/"$torepl"/
echo "$exp"
sed -e "$exp" Makefile > X
mv X Makefile

